default_model: openai

openai:
  api_key: null # optional if you use .env
  temperature: 0.7
  max_tokens: 600

openai_image:
  api_key: null # optional if you use .env
  model: "gpt-image-1"
  size: "1024x1024"
  quality: "high"  

anthropic:
  api_key: null     # optional if you use .env
  model: "claude-3-haiku"
  temperature: 0.7
  max_tokens: 600
