name: AI Invoice Extractor Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ai-invoice-extractor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AI_INVOICE_EXTRACTOR_TOKEN }}
        run: bun publish --access public
