name: AI Invoice Extractor CI

on:
  push:
    paths:
      - 'ai-invoice-extractor/**'
  pull_request:
    paths:
      - 'ai-invoice-extractor/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ai-invoice-extractor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

    #   - name: Run tests
    #     run: bun run test

      - name: Build project
        run: bun run build
